### ISSUE TITLE
How do I get my RegistrationView to create another model on object creation?

### ISSUE THREAD

**Issue by AlexCreamer** [ubernostrum/django-registration#105]
I see there's a register function within the RegistrationView class that may get called when a registration as seen here: https://github.com/ubernostrum/django-registration/blob/master/registration/views.py#L59

I tried creating a register functions but it didn't get called

**Comment by AlexCreamer** [comment]
Changing the register method did get it called but how I can reuse the impementation done by django-registration?

**Comment by ubernostrum** [comment]
You need to also point your URLs at your subclass, rather than using the default URLconf.
