### ISSUE TITLE
Needed: a way to allow user registration without a user-supplied password

### ISSUE THREAD

**Issue by ri0t** [ubernostrum/django-registration#108]
I need users to register without providing a password. 
Ideally, the password would be auto-generated from a random string. 
So, to log in, users would need to wait for their account to be activated and could then access the "forgot my password" function to actually get the password.

Is that or something similar  possible at all?

**Comment by ubernostrum** [comment]
It sounds like you could write a registration workflow for this, yes. Just subclass the views as mentioned in the documentation.
