### ISSUE TITLE
Password-Reset Email-Template Changed in v2.3 for Django 1.11+

### ISSUE THREAD

**Issue by jambonrose** [ubernostrum/django-registration#113]
The behavior of the password reset feature changes when either (1) upgrading `django-registration` from 2.2 to 2.3 on a Django 1.11+ site or else (2) upgrading from Django 1.x to 1.11 with `django-registration` v2.3 installed. The password reset email template used by `django-registration` changes depending on whether function views or class-based views are used by [`auth_url_module`](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls.py#L23).

In `django-registration` 2.2 and with v2.3 [function auth views](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls_functions.py), the password reset view email template is [overridden to `registration/password_reset_email.txt`](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls_functions.py#L42). However, the 2.3 [class auth views](https://github.com/ubernostrum/django-registration/blob/cd8430d5074bfe6f4c7931a3f37ea67511ea9be2/registration/auth_urls_classes.py) use Django's default email template, which is [`registration/password_reset_email.html`](https://github.com/django/django/blob/stable/1.11.x/django/contrib/auth/views.py#L426) (note the difference in file extension).

What's more, if `'django.contrib.admin'` appears in the INSTALLED_APPS list before a local app that provides a local `registration/password_reset_email.html`, the the site will use [Django's template](https://github.com/django/django/blob/stable/1.11.x/django/contrib/admin/templates/registration/password_reset_email.html). That can be a problem, as the template attempts to reverse to a URL named `'password_reset_confirm'`, which does not exist on the site if the developer is relying on `django-registration` URLs (the view is instead `auth_password_reset_confirm`).

Given current behavior, developers either have the choice of (1) writing out their own URL configuration (optimal, but more work), (2) changing the order of their INSTALLED_APPS (undesirable), (3) adding a duplicate set of Django auth views (terrible).

If `registration.auth_urls` were intended as a long-term feature, I would advocate sticking with Django's defaults and simply noting the backwards-incompatible change in a change-log. However, given that the intent is to remove `registration.auth_urls` in v3.0 (as noted in #78), I suspect that a patch to make the class-based views use the same template as function views and previous releases may be the best solution.

**Comment by jambonrose** [comment]
Once a decision has been made to the right course-of-action (if any), I'm happy to help with a PR.

**Comment by ubernostrum** [comment]
If you've got a patch that lets the 2.3 series work, I'd be happy to accept it and roll out a point release. 2.3 will be the last release series to include auth URLs, so it'd be nice to have them in a working state for people who never upgrade beyond it.

**Comment by jambonrose** [comment]
I'll be in touch Sunday with a PR.

**Comment by Sonictherocketman** [comment]
Has a version been pushed with this fix? Still seeing it with Django 1.11.

**Comment by justinmayer** [comment]
@Sonictherocketman: No, otherwise #114 would be merged and this issue closed.
