### ISSUE TITLE
Error in registration.views.ActivationView.get()

### ISSUE THREAD

**Issue by cpattersonit** [ubernostrum/django-registration#116]
Hello,

I have been successfully using this package with version 2.2 in a Django 1.11.6 project with Python 2.7.14. In order to substitute my own success_url in the HMAC ActivationView, I was forced to subclass the package view and override the get_success_url() method. However, I ran into a problem after upgrading the package to the latest release (2.3), due to a change in the get() method of the base ActivationView:

            success_url = self.get_success_url(activated_user) if \
                (hasattr(self, 'get_success_url') and
                 callable(self.success_url)) else \
                self.success_url

This code is causing a redirect to self.success_url instead of the result of my get_success_url() method. I believe there is a mistake in this snippet, based on the similar snippet located in the new version of the form_valid() method of the base RegistrationView:

        success_url = self.get_success_url(new_user) if \
            (hasattr(self, 'get_success_url') and
             callable(self.get_success_url)) else \
            self.success_url

As you can see, the RegistrationView code checks if get_success_url exists and is callable, while the ActivationView code checks if get_success_url exists and self.success_url is callable. The end result is that this change/mistake breaks my code that is depending on it and is, therefore, backwards incompatible. 

I corrected the error in my installed package, and it fixed my app. Can you please correct this error in the codebase?

Thanks,
Christopher Patterson
cpattersonit@gmail.com

**Comment by ubernostrum** [comment]
Pretty sure [this PR will fix it once merged](https://github.com/ubernostrum/django-registration/pull/111).
