### ISSUE TITLE
User object has no attribute `email_user`?

### ISSUE THREAD

**Issue by surfer190** [ubernostrum/django-registration#117]
`'User' object has no attribute 'email_user'`

During registration in: `site-packages/registration/models.py in send_activation_email`

` self.user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)`

**Comment by surfer190** [comment]
So I was forced to add that method to my Custom User model:

```
    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)
```

**Comment by ubernostrum** [comment]
From the documentation:

https://django-registration.readthedocs.io/en/2.3/custom-user.html

> Additionally, your user model must implement the `email_user` method for sending email to the user.
