### ISSUE TITLE
Yet another request for HTML email support

### ISSUE THREAD

**Issue by tobltobs** [ubernostrum/django-registration#121]
An anecdote to support the request for html emails: 

I changed my emails sending provider because my last one wasn't reliable enough. This last provider did automatically convert text emails to html emails, so he could insert the open tracking pixels. The new one does not do that. The final result of the switch. Email delivery went up from 90% to 98% with the new provider. But the percentage of never activated accounts also went up from 15% to 22%. 

It turns out that a lot of users have problems using the link in a plain text email. Some email clients do not convert it into a clickable link and people fail copy and pasting it into the address bar ("What is the address bar?", "You mean into Google?"). Some other clients convert it to a link, but only up to the colon, which of course also fails.

Now I have to create yet another custom solution to extend the otherwise awesome django-registration.

**Comment by ubernostrum** [comment]
Once again, I have no plans to make HTML email be the default in django-registration. It's easy enough to generate HTML emails if you want them.

**Comment by zbyte64** [comment]
Okay...

What is the recommended way of sending HTML registration emails with this project? 

But seriously, am I suppose to monkey patch RegistrationProfile?

**Comment by mscheper** [comment]
@zbyte64: The way I would recommend is to replace this library with [django-registration-redux](https://github.com/macropin/django-registration) (docs [here](https://django-registration-redux.readthedocs.io/en/latest/index.html)), which comes with HTML emails out of the box. Pretty much everything works out of the box, actually; I wish I'd seen it before I spent a day fiddling around with this legacy library, manually creating templates and getting them to work.

The good news is that replacing this library with the 'redux' version was pretty straightforward, and I haven't noticed any disadvantage. The only thing that wasn't documented obviously to me is that the reverse lookup for a logout URL is `{% url 'auth_logout' %}`.
