### ISSUE TITLE
New minor version (2.3.1)

### ISSUE THREAD

**Issue by vstoykov** [ubernostrum/django-registration#122]
Currently django registration relies on confusable_homoglyphs 2.x which is kind of broken by design regarding data files. In version 3 this is fixed and data files are redistributed with the package.

I have issues with running tests on our CI for a project using django-registration if I try to upgrade from 2.2 to 2.3. 

In current master requirements are set to ~3.0. For that reason I'm suggesting releasing 2.3.1 (if there are not any PR which are urgent and the release of 2.3.1 need to wait for tem).

**Comment by xrmx** [comment]
Yes please! had to revert to 2.2 for all my projects because 2.3 breaks tests or in one instance even the django project startup under uwsgi.

**Comment by ubernostrum** [comment]
Latest release is out and resolves this.
