### ISSUE TITLE
Support generating an optional html message

### ISSUE THREAD

**Issue by zbyte64** [ubernostrum/django-registration#126]
Registration emails currently only support plain text. Django `send_mail` function support an `html_message` argument for sending an alternate HTML representation of the email. django-registration should consult an additional template (if enabled) to supply the HTML content.

**Comment by justinmayer** [comment]
Hi Jason. Did you check the closed issues list first? You should see #121, from four days ago, as a recent example. I believe that James, the project maintainer, has already made his position on this topic quite clear.

**Comment by zbyte64** [comment]
Sorry.
