### ISSUE TITLE
Suggestion: add request to render_to_string when sending out emails

### ISSUE THREAD

**Issue by typistX** [ubernostrum/django-registration#128]
This will allow the usage of "global variables" defined in custom context processors. Currently we have to override each corresponding view that utilizes email sending. I'd send a PR myself if I had the experience, but my suggestion is pretty basic:

    def send_activation_email(self, user):
        """
        Send the activation email. The activation key is the username,
        signed using TimestampSigner.
        """
        activation_key = self.get_activation_key(user)
        context = self.get_email_context(activation_key)
        context.update({
            'user': user,
        })
        subject = render_to_string(self.email_subject_template,
                                   context)
        # Force subject to a single line to avoid header-injection
        # issues.
        subject = ''.join(subject.splitlines())
        message = render_to_string(self.email_body_template,
                                   context)
        user.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)

The only thing to change, I think, is this:

```
subject = render_to_string(self.email_subject_template,
                                   context, request=self.request)

message = render_to_string(self.email_body_template,
                                   context, request=self.request)
```

This allows for the usage of global variables defined in the processors. I'm fully aware context can be passed individually, but the whole premise of the suggestion is to allow the usage of global-like variables.

**Comment by dahrens** [comment]
I did a short investigation. Next to the view there is also a method on the `RegistrationProfile` model - it gets utilized in the admin to be able to resend activation emails there as well.

```python
class RegistrationProfile:
    def send_activation_email(self, site):
        pass
```

This also needs the request passed for this to work properly. As you currently pass `site` there it might be replaced with request, as the site can be fetched from the request using `django.contrib.sites.shortcuts.get_current_site`

Side-Note: There seems to be only one view that sends an E-Mail in hmac backend: `RegistrationView`

**Comment by ubernostrum** [comment]
The model-activation backend is deprecated and scheduled to be removed in a near-future version of django-registration. And adding the request to the context for the email there would be a backwards-incompatible change since it requires changing several argument signatures.

So this can't be done yet.
