### ISSUE TITLE
Option for case-insensitive uniqueness of usernames

### ISSUE THREAD

**Issue by edelans** [ubernostrum/django-registration#137]
Hello, 

I just read the great article In [Let's talk about usernames](https://www.b-list.org/weblog/2018/feb/11/usernames/) from @ubernostrum .

I understand case-insensitive uniqueness of usernames is tricky to implement because of the huge bc-break it represents.

> This is a simple thing that a lot of systems get wrong. In researching for this post, I discovered Django’s auth system doesn’t enforce case-insensitive uniqueness of usernames, despite getting quite a lot of other things generally right in its implementation. There is a ticket for making usernames case-insensitive, but it’s WONTFIX now because making usernames case-insensitive would be a massive backwards-compatibility break and nobody’s sure whether or how we could actually do it. I’ll probably look at enforcing it in django-registration 3.0, but I’m not sure it’ll be possible to do even there — any site with existing case-sensitive accounts that bolts on a case-insensitive solution is asking for trouble.

May I suggest implementing this as an opt-in (with default to `true`) instead of making it mandatory ? It would make your suggestion easier to implement.  

> So if you’re going to build a system from scratch today, you should be doing case-insensitive uniqueness checks on usernames from day one;

Thanks again for the great article on usernames.

**Comment by ubernostrum** [comment]
I'm still debating whether to do this; the large existing install base is problematic.

Most likely what I'll end up doing is writing a case-insensitive `RegistrationForm` class, and figuring out some way to nudge people to use it for new projects.
