### ISSUE TITLE
Extra reserved names

### ISSUE THREAD

**Issue by Xeoncross** [ubernostrum/django-registration#138]
I noticed that some words (like "payment") are missing while ["payments" is listed](https://github.com/ubernostrum/django-registration/blob/master/registration/validators.py#L150). What were the design decisions about what words count as important?

- authorize (https://github.com/login/oauth/authorize)
- callback (https://teletype.atom.io/auth/teletype/callback)
- payment
- store
- cart
- `.git`
- `.svn`

[500+ more reserved words for usernames](https://github.com/shouldbee/reserved-usernames) and [postbit reserved usernames](https://softwareengineering.stackexchange.com/a/115427/4331)

**Comment by salmanulfarzy** [comment]
There are some explanation in the article [Let’s talk about usernames](https://www.b-list.org/weblog/2018/feb/11/usernames/).
