### ISSUE TITLE
pip installing version 1.0 not latest version

### ISSUE THREAD

**Issue by dmoccia** [ubernostrum/django-registration#14]
Hello

Not sure if this is something I did on my end or not but I tried a "pip install django-registration" and version 1.0 of the package was installed.  I tried "pip install django-registration==1.8" and received a message:

```
Could not find a version that satisfies the requirement django-registration==1.8 (from versions: 0.7, 0.8, 1.0)
No matching distribution found for django-registration==1.8
```

I can always do a manual install but I thought I might check with you first on reasons why this may be happening?

**Comment by c0d3z3r0** [comment]
I had the same problem. It seems there is just 1.0 at pypi.
You can install from github: pip install https://github.com/ubernostrum/django-registration/archive/master.zip

**Comment by ubernostrum** [comment]
1.8 has not been released, so there is no bug here. When 1.8 is released, it will be on PyPI.

**Comment by dmoccia** [comment]
Sorry my mistake, I figured it was released when I came across the
documentation.
