### ISSUE TITLE
Support for Django 2.x

### ISSUE THREAD

**Issue by jp-um** [ubernostrum/django-registration#155]
More of a question than an issue.  Does django-registration support Django 2.x ?

**Comment by philmaweb** [comment]
Actually, it looks like it's not supported. When looking at the buildscripts for the tests at https://travis-ci.org/ubernostrum/django-registration/jobs/392925408 they specify: 
`py36-django111` installdeps: -rtest_requirements.txt, Django>=1.11,<2.0

**Comment by ubernostrum** [comment]
3.x will support Django 2.0 from the get-go.

Once it's out, I'll do a final 2.x release and bump the compatibility indicators. For now, the only thing that's likely to break is the auth URL setup.

**Comment by marinbek** [comment]
Thanks for all you work @ubernostrum! Do you have some timeline for 3.x release, some 'unstable' where we can help with testing/fixing etc.?

**Comment by zout** [comment]
@ubernostrum Since this 3.0 release seems to be stalled (no judging, just an observation), can we at least merge a MR in that enables the world to use Django 2.0?

That would be very much appreciated. 

PS: As of now, Django 2.0 has been released 260 days ago.

**Comment by ubernostrum** [comment]
Closing as of 8e1559b1d6144c7a156a8e6e7dfd30331a132954.

With 2.5 out the door, there will be no further 2.x releases.
