### ISSUE TITLE
Pip reports that Django 1.9.x is not supported

### ISSUE THREAD

**Issue by NazarTopolsky** [ubernostrum/django-registration#159]
While installing django-registration for my project that still uses Django 1.9, I have encountered a peculiar error. If I explicitly specify Django and django-registration versions like this:

    pip install django-registration==2.4.1 django==1.9.13

everything goes smoothly.

However, if I install django-registration first, and then downgrade to Django 1.9, I get the following output:

    Collecting Django==1.9.13
      Using cached https://files.pythonhosted.org/packages/a6/ee/6dfd9e8e0d61ab22ed09c6c8f6ae5a4ad0d3bf07bca9124fb5a087f876df/Django-1.9.13-py2.py3-none-any.whl
     django-registration 2.4.1 has requirement Django!=1.9.*,<2.0,>=1.8, but you'll have django 1.9.13 which is incompatible.
      Installing collected packages: Django
        Found existing installation: Django 1.11.14
          Uninstalling Django-1.11.14:
            Successfully uninstalled Django-1.11.14
    Successfully installed Django-1.9.13

Documentation states that [Django 1.9 is supported](https://django-registration.readthedocs.io/en/2.4.1/install.html#installation-guide):

>The 2.4.1 release of django-registration supports Django 1.8, 1.9, 1.10 and 1.11, on the following Python versions:

I tend to trust documentation over pip output, and the code seems to work, but it is strange.

**Comment by ubernostrum** [comment]
It's an error in the documentation. Django 1.9 is not supported; django-registration only officially supports upstream-supported versions of Django, and at the time of the 2.4.1 release Django 1.9 was past end-of-life.
