### ISSUE TITLE
Simplify the usage of a custom RegistrationForm

### ISSUE THREAD

**Issue by tdruez** [ubernostrum/django-registration#163]
Declaring a custom `RegistrationForm` requires to mess with the urlpatterns at the moment. See https://django-registration.readthedocs.io/en/2.4.1/custom-user.html#overview

This works fine, but what about offering this customization through a new `REGISTRATION_FORM` settings to simply things a bit?

It only requires a small change in the codebase https://github.com/ubernostrum/django-registration/blob/master/src/django_registration/views.py#L24
```
form_class = RegistrationForm
```
 -> 
```
form_class = getattr(settings, 'REGISTRATION_FORM', RegistrationForm)
```

@ubernostrum let me know your thoughts on this.

**Comment by ubernostrum** [comment]
I prefer not to proliferate settings. I especially prefer not to proliferate them when Django itself provides a mechanism for doing what you want (write your own single URL pattern, passing your preferred form as an argument to the view).
