### ISSUE TITLE
NotImplemented Error in RegistrationView

### ISSUE THREAD

**Issue by tBaxter** [ubernostrum/django-registration#167]
Let me preface this by saying I'm replacing a _very_ old copy of django registration, a lot has moved in the interim, and in all likelihood this is my error. But that said, I'm not seeing how the current version works.

What I'm seeing is a NotImplemented error raised by RegistrationView.register (https://github.com/ubernostrum/django-registration/blob/master/src/django_registration/views.py#L62) As I trace it back, I see register is called by form_valid (https://github.com/ubernostrum/django-registration/blob/master/src/django_registration/views.py#L49) so I'm not seeing how a valid form wouldn't raise the error. 

Can you clarify?

Thank you, and also, let me thank you for the years of hard work and careful though i know you've put into this. It shows, and I doubt I'd trust any other registration solution.

**Comment by ubernostrum** [comment]
The base `RegistrationView` is never ever meant to be actually used as a view; you are absolutely required to either use one of the subclasses of it provided in the app (see the documentation), or write your own subclass if your preferred registration workflow doesn't match the built-in ones (again, see the documentation).

**Comment by tBaxter** [comment]
Thank you James. That makes perfect sense.
