### ISSUE TITLE
MINOR: two email title lines, when merged need a space, not empty str

### ISSUE THREAD

**Issue by griswolf** [ubernostrum/django-registration#169]
file: django_registration/backends/activation/views.py
line: 104 in send_activation_email
Original:
        `subject = ''.join(subject.splitlines())`
Better:
        `subject = ' '.join(subject.splitlines())`

Note that this assumes no blank lines. Blank lines will be replaced by two spaces

**Comment by ubernostrum** [comment]
This is actually deliberate -- I want the subject line to look "broken" so the person who wrote the template will go investigate why, and figure out they tried to do a multi-line subject.
