### ISSUE TITLE
Rename activation to two_steps

### ISSUE THREAD

**Issue by unho** [ubernostrum/django-registration#179]
Recently "HMAC" was renamed to "two-step" in the documentation, but the Python module was renamed from `hmac` to `activation` (see commit https://github.com/ubernostrum/django-registration/commit/a882cd99).

This is a misalignment that doesn't happen with "one-step" activation workflow which got renamed from "Simple" to "one-step" and `simple` to `one_step` (see commit https://github.com/ubernostrum/django-registration/commit/35b29497).

I suggest renaming the Python code from `activation` to `two_steps`.

**Comment by ubernostrum** [comment]
This would be backwards-incompatible, so couldn't happen until at least django-registration 4.0. It's also probably not something I'm going to do. The names aren't meant to be symmetric; they're meant to be descriptive.
