### ISSUE TITLE
Example Templates?

### ISSUE THREAD

**Issue by aaronn** [ubernostrum/django-registration#183]
I noticed this in the FAQ:

`Providing default templates with an application is ranges from hard to impossible, because different sites can have such wildly different design and template structure. Any attempt to provide templates which would work with all the possibilities would probably end up working with none of them.`

I think it'd be helpful to have a barebones template example, even if nobody is going to use it in production as-is.

**Comment by ubernostrum** [comment]
I'm still not planning to include default templates. If they're included, large numbers of people will try to use them, and then will come complain to me when those templates don't work with their site.

**Comment by jonathan-s** [comment]
One more vote for example templates. I would suggest that you base them on how admin looks. Right now there is no registration functionality for admin.

**Comment by everythingability** [comment]
FFS... The templates can do the basics with an {%extends base.htm%} and a content block.... from there people can do whatever they like
