### ISSUE TITLE
Following the quickstart guide now raises NoReverseMatch at /accounts/register/  'accounts' is not a registered namespace

### ISSUE THREAD

**Issue by Kimonode** [ubernostrum/django-registration#185]
In absence of proper app_name and namespace, templates must hardcode the urls, e.g. /accounts/register.

Using tags {% url %} raises an Exception, e.g. "NoReverseMatch at /accounts/register/  'accounts' is not a registered namespace" when trying to access the URL /accounts/register/ 

Having the ability to define a namespace would be nice.

**Comment by ubernostrum** [comment]
You can specify a namespace when you `include()` the URLs.
