### ISSUE TITLE
Using `UserCreationForm`

### ISSUE THREAD

**Issue by jonathan-s** [ubernostrum/django-registration#187]
The UserCreationForm uses `django.contrib.auth.models.User` not the user used in settings. So when you use the registrationform with a custom user model this will fail. 

https://github.com/django/django/blob/master/django/contrib/auth/forms.py#L94

I would say that the core issue lies in django, but getting a fix upstream will probably take longer than getting a fix here.

**Comment by ubernostrum** [comment]
The base `RegistrationForm` is deliberately set up this way to force you to write your own form when using a custom `User` model. That reduces the chance of someone having a `User` model that accidentally mostly works with the default form and then breaks mysteriously later on.
