### ISSUE TITLE
Activation key not found

### ISSUE THREAD

**Issue by jonathan-s** [ubernostrum/django-registration#189]
To get the activation key in the activation view I would assume that it's intended to use the get parameter. Instead it only uses kwargs which means that no key is found. Subsequently a 500 error will be thrown since it's trying to unsign an empty value. 

https://github.com/ubernostrum/django-registration/blob/master/src/django_registration/views.py#L95

The correct way would be to use `self.request.GET.get('activation_key')`

**Comment by ubernostrum** [comment]
It is not intended to be a querystring parameter. You could subclass and override if you wanted to do that, but the usual case is that the key is in the URL itself (see the activation backend's URL patterns and views for an example).

**Comment by jonathan-s** [comment]
Thank you. Perhaps this could be an improvement to the documentation, considering that particular configuration is not mentioned there -> https://django-registration.readthedocs.io/en/3.0.1/activation-workflow.html#behavior-and-configuration

You are correct that I could have looked at the urls `django_registration.backends.activation.urls`, but it was something that I overlooked.
