### ISSUE TITLE
Dependency removed in django 3.0

### ISSUE THREAD

**Issue by stgoddv** [ubernostrum/django-registration#197]
As you can see from https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils:

django.utils.six - Remove usage of this vendored library or switch to six.

That's used in "validators.py" in you package.
Need to change:
from django.utils import six

To
import six

**Comment by ubernostrum** [comment]
Hi, as you can see if you check the trove classifiers, the 3.0.1 release of django-registration did not support Django 3.0. As you can see if you check the current master branch which will become django-registration 3.1, support for Django 3.0 is planned there. And as you can see if you look at recent commits, Django 3.0 compatibility has already been handled in the master branch.

In the future, please keep in mind that every bug report takes time and generates work for the maintainer of an open-source project, and do some basic checks -- like looking at the declared compatibility for release versions, and recent commits in the master branch -- before filing a bug, as that may help prevent you from re-reporting something that was already known and fixed.

**Comment by barseghyanartur** [comment]
@ubernostrum:

Do you by any chance have an estimate on when a release supporting Django 3.0 could be expected?
