### ISSUE TITLE
Cannot import name 'six' from 'django.utils' with Django 3.0

### ISSUE THREAD

**Issue by moniquemurphy** [ubernostrum/django-registration#198]
If using Django 3.0, the `six` package is now imported with `import six`, no longer from `django.utils`. This causes an error in validators.py.

**Comment by ubernostrum** [comment]
The latest packaged release of django-registration (3.0.1) was released prior to Django 3.0. The next packaged release of django-registration will add Django 3.0 compatibility, and [the master branch already contains the fixes](https://github.com/ubernostrum/django-registration/commit/1cb594cd71ba3d510f17ec37ed4ecb33c0520ab2#diff-b753ba9ad6e65d50d9e687c28771613a).

I do not at this time have an estimate of the date on which the next packaged release of django-registration will occur, as that release will be completely dropping Python 2 support, which is a slighlty more complex issue than just changing some imports.
