### ISSUE TITLE
Templates?

### ISSUE THREAD

**Issue by everythingability** [ubernostrum/django-registration#204]
Are there not any example templates for this?  The docs say I would have to create a heap of them.... with no idea of what should be in them...

Thanks

Tom

**Comment by ubernostrum** [comment]
The documentation lists the templates you will need to create, explains the purpose of each, and gives you the context listing for each. This should be sufficient to create the templates.

As to whether there are any built-in, [the documentation answers that question, too](https://django-registration.readthedocs.io/en/3.1/faq.html#does-django-registration-come-with-any-sample-templates-i-can-use-right-away).
