### ISSUE TITLE
wrong path to include in my site URL configuration.

### ISSUE THREAD

**Issue by mohammed123saleh** [ubernostrum/django-registration#212]
in the documentation for Django-registration there is wrong path to include in my site URL configuration. while in the documentation we should add this path:
urlpatterns = [
    # Other URL patterns ...
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

this path does not work because it does not exist the right path is :
urlpatterns = [
    # Other URL patterns ...
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

**Comment by ubernostrum** [comment]
It appears you are trying to use the documentation for the current version, with code from an old version. This will not work. the correct location in the current version of django-registration is `'django_registration.backends.one_step.urls`. You can prove this by looking at [the actual code](https://github.com/ubernostrum/django-registration/blob/3.1/src/django_registration/backends/one_step/urls.py). Notice that file is located in the folder `django_registration/backends/one_step`, and that there is no folder named `registration/backends/simple`.

Either install the current version of django-registration, or check the version you are using and then read the documentation for that version.
