### ISSUE TITLE
django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy()

### ISSUE THREAD

**Issue by Ben-yeah** [ubernostrum/django-registration#215]
Hello, The only thing I'm personally see wrong with Treebeard and Django 3.0 is that 3.0 officially deprecated ugettext_lazy, and if you run python -Wall, you'll get a ton of RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy(). from Registration's code.

**Comment by ubernostrum** [comment]
I'm unable to find any usage of `ugettext_lazy()` remaining in the current main branch.
