### ISSUE TITLE
Translation for "Password" does not work

### ISSUE THREAD

**Issue by kwankyu** [ubernostrum/django-registration#217]
I am using `django-registration` for an website in Korean language. I have `{% trans 'Password' %}` in the registration_form.html (and also in `login.html`) and provided translation `비밀문자` to override the default `사용자 패스워드` provided by `django-registration` (Django's default translation is `비밀번호`, by the way). But my custom translation does not work. It shows `사용자 패스워드`.

I checked that removing `django-translation` from the `INSTALLED_APPS` setting makes it work normally. So it seems `django-registration` somehow interferes with the custom translation.

I have no idea how to fix the bug. Thank you for attention.

**Comment by ubernostrum** [comment]
I'm also not sure what would be causing this. If you do find out, let me know and I'll fix it.
