### ISSUE TITLE
i18n translation doesn't work.

### ISSUE THREAD

**Issue by quroom** [ubernostrum/django-registration#222]
![image](https://user-images.githubusercontent.com/39736691/102310198-df1c5480-3fad-11eb-9d4f-8986f430b068.png)
![image](https://user-images.githubusercontent.com/39736691/102310227-ec394380-3fad-11eb-9593-e4b547e000dc.png)

As you can see, 
gettext_lazy doesn't get translation text properly.
I debugged but the translation key, which is in django-registration doesn't match to ko message.
I check po file for ko, en. But there is no problem.
But I don't know why.

**Comment by ubernostrum** [comment]
I believe the Korean translation file for django-registration is not up to date. If you'd like to supply new translations I'd be happy to accept a patch.

**Comment by quroom** [comment]
I misunderstood how django translation works.
I didn't know I have to copy po message to my local locale file.
I thought django discover locale file in third file package.
but it doesn't find third party package locale file.

Anyway I will send PR for korean translation someday.
Thanks for your answer and your great package. Have a nice day.
