### ISSUE TITLE
Undocumented assumption about custom user models

### ISSUE THREAD

**Issue by kokolem** [ubernostrum/django-registration#241]
The two-step activation workflow's RegistrationView expects the user object to have a email_user method: https://github.com/ubernostrum/django-registration/blob/7a1d8609b7c262f0321bbb39a6f901b9a6953cce/src/django_registration/backends/activation/views.py#L106 This is true for custom user models that inherit from AbstractUser, but not for those that inherit from AbstractBaseUser. I belive this should be documented in Compatibility of the built-in workflows with custom user models section.

**Comment by ubernostrum** [comment]
As noted over in [#234](https://github.com/ubernostrum/django-registration/issues/234#issuecomment-1583787388), I'm already planning to do a new major version which will focus on the custom-user handling. So I'll look into fixing the documentation for now, but also the main focus is going to be on making the whole thing less brittle.

**Comment by ubernostrum** [comment]
WIP of the rewrite of `RegistrationForm` is in this branch: https://github.com/ubernostrum/django-registration/tree/remove-usercreationform
