### ISSUE TITLE
Python 3.11+ support?

### ISSUE THREAD

**Issue by norchai** [ubernostrum/django-registration#243]
I noticed the FAQ says Python 3.10 is supported but doesn't mention newer versions.  Has django-registration been tested against any of them?  Is the FAQ out of date?  If not, what plans are there for 3.11/3.12/future version support?

**Comment by ubernostrum** [comment]
It should work fine; there's no backwards-compatibility breakage in those releases. I just haven't done a release to explicitly say it's compatible, mostly because Django is the moving target and I wanted to do a release for 5.0 (soon).
