### ISSUE TITLE
I get a NoReverseMatch using 5.1.0 and django 4.2.17 after trying to create an account

### ISSUE THREAD

**Issue by frankystone** [ubernostrum/django-registration#251]
Maybe i am doing something wrong but with previous version of django-registration the code we used did work.

With v 5.1.0:
After creating an account an error like this occurs:
~~~~
django.urls.exceptions.NoReverseMatch: Reverse for 'django_registration_activate' with arguments '('InBldGVyIg:1tP18x:N53el-Wx02OqK5ciG6et122W_Uz_ZhYorS5Mz8tQX7A',)' not found. 1 pattern(s) tried: ['accounts/activate/\\Z']
~~~~

The code which raises it is `http://{{ site }}{% url 'django_registration_activate' activation_key %}` and is used in  [activation_email_body.txt](https://github.com/widelands/widelands-website/blob/84994b31c9b0b9a9936006909a78c9a3ead988c8/templates/django_registration/activation_email_body.txt) and the error prevents sending the registration e-mail.

Trying to apply the activation-key given in the exception above to a url like `http://localhost:8000/accounts/activate/InBldGVyIg:1tP18x:N53el-Wx02OqK5ciG6et122W_Uz_ZhYorS5Mz8tQX7A`  gives the error `Page not found` with those urls tried

~~~~
Using the URLconf defined in mainpage.urls, Django tried these URL patterns, in this order:

^sitemap\.xml
^robots\.txt
^admin/
^accounts/register/$ [name='django_registration_register']
accounts/ activate/complete/ [name='django_registration_activation_complete']
accounts/ activate/ [name='django_registration_activate']
[ ... ]
~~~~

Urls set, according to the documentation:
~~~~
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
~~~~

If i change the url-path in [src/django_registration/backends/activation/urls.py](https://github.com/ubernostrum/django-registration/blob/b0a2e49e2127dc8a51a43435a88c13ca37087a7e/src/django_registration/backends/activation/urls.py#L23) to `"activate/<str:activation_key>/"`, the NoReverseMatch error is gone and the E-Mail is send. The provided link in the E-Mail opens then the `django_registration/activation_form.html` .

Is there an issue with the url-path in `django_registration/backends/activation/urls.py`, or am i doing something terrible wrong?

Thanks for any answer :-)

**Comment by ubernostrum** [comment]
The activation key is now expected as a querystring parameter, rather than as a captured URL parameter. See [the documentation for the activation view](https://django-registration.readthedocs.io/en/stable/activation-workflow.html#django_registration.backends.activation.views.ActivationView).

**Comment by frankystone** [comment]
Ahhh, thanks for the pointer.
