### ISSUE TITLE
HMAC activation workflow / User registration with empty e-mail address

### ISSUE THREAD

**Issue by pitervergara** [ubernostrum/django-registration#31]
Hi,

I'm using django-registration==2.0.3 (with Django==1.9.1). When using the HMAC workflow, the user is able to submit the form without an e-mail address, since this is an optional field in the user model. When the e-mail is empty the flow breaks with an SMTP error.

Am I missing something about the configuration? There is a built-in way to avoid this problem?

thanks!

**Comment by ubernostrum** [comment]
There'll be a 2.0.4 release soon fixing this. For now, in both master and in the 2.0.x branch here on github, it's fixed.

**Comment by ubernostrum** [comment]
2.0.4 is now on PyPI.

There'll also be a 2.1 release soon for Django 1.9 compatibility.

**Comment by pitervergara** [comment]
Hi,
I've tested here. Problem solved, e-mail is now a required field in my form.
Thanks for your attention on this issue!
