### ISSUE TITLE
Please rename the python package: registration -> django_registration

### ISSUE THREAD

**Issue by absurd34** [ubernostrum/django-registration#32]
Hi James, maintainers,

please consider doing this, keeping a compatibility package "registration" (including a deprecation warning) around as long as needed.

Having a django-specific python package called "registration" around is confusing, and takes away this name for other possible uses (namespace pollution).

Current practice for third party django packages seems to be the "django_PACKAGE/" scheme, so I am suggesting this (don't use "django/PACKAGE" as maybe suggested elsewhere, this would pollute django's project namespace).

Fwiw, this is a followup to

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=567739

Thank you for considering!

Stephan

**Comment by ubernostrum** [comment]
At this time I have no plans to rename the module, since as you point out I'd need to keep a backwards-compatible fallback which would itself just "pollute" the namespace.

If distros want to package it under a different Python module name that's their call.

**Comment by absurd34** [comment]
Hi James,

thanks for the quick reply; however...

On Mi, 2016-01-13 at 10:53 -0800, James Bennett wrote:
> At this time I have no plans to rename the module, since as you point out I'd need to keep a backwards-compatible fallback which would itself just "pollute" the namespace.

... I do actually strongly disagree here.

This would merely pave the way so you can eventually (maybe in some
version 3.0 or 4.0) get rid of the fallback and the "pollution"
entirely.

> If distros want to package it under a different Python module name that's their call.

This would make thing worse by far ;). For one thing, it would make
django apps incompatible between distros.

I.e., upstream is king here, I will follow ;).

Maybe, for documentation purposes, could label this "wontfix" or
"wishlist" (if github supports such a thing)?

Thx!

Stephan
