### ISSUE TITLE
Absolute URL in Email

### ISSUE THREAD

**Issue by dbrgn** [ubernostrum/django-registration#36]
Is there a way to build an absolute URL in the activation e-mail? The request does not seem to be available in the `activation_email.txt` template.

I see that you're passing in the `site` parameter, so you probably expect that this should be done through the sites framework. But since 1.8 (iirc) this is not enabled by default. Also, I don't want to put an URL configuration in my database if it can just live in the settings or be built from the request info.

Therefore, it would be great if you could pass in the `request` parameter to the context (see [render_to_string docs](https://docs.djangoproject.com/en/1.8/topics/templates/#django.template.loader.render_to_string)).

**Comment by ubernostrum** [comment]
The `site` parameter is generated by calling `get_current_site()`, which automatically checks whether the sites framework is installed and falls back to a `RequestSite` object if the sites framework is not installed, which means you do not need to install the sites framework to have this work.

**Comment by dbrgn** [comment]
Whoa, I didn't know that yet. Great :)
