### ISSUE TITLE
Is there a way to set it to require manual activation?

### ISSUE THREAD

**Issue by the-mace** [ubernostrum/django-registration#39]
I want to use the whole registration workflow, but require manual approval for a beta period to avoid open access. Is there a setting/way to do that?

Thanks for the great app.

**Comment by ubernostrum** [comment]
You could write a registration workflow which does that. There isn't one built in, but it wouldn't be too hard -- just a `RegistrationView` subclass which creates an inactive account, and then wire up either an admin action or a (permission-protected) view for seeing who's registered and activating their accounts manually.
