### ISSUE TITLE
table name errro on custom user model

### ISSUE THREAD

**Issue by maxxxir** [ubernostrum/django-registration#41]
i have a custom user model which basically changes user table name from auth_user to customuser

```
from django.db import models
from django.contrib.auth.models import AbstractUser
class customuser(AbstractUser , models.Model):
    class Meta:
        swappable = 'AUTH_USER_MODEL'
        db_table = 'customuser'
```
and in my settings i have 

`AUTH_USER_MODEL = 'customuser.customuser'`

so every thing works i can login , change my password  but only when i try to register i get this error

> ProgrammingError at /auth/register/
> 
> (1146, "Table 'django_usertest.auth_user' doesn't exist")
> 
> Request Method: 	POST
> Request URL: 	http://localhost:8000/auth/register/
> Django Version: 	1.9.6
> Exception Type: 	ProgrammingError
> Exception Value: 	
> (1146, "Table 'django_usertest.auth_user' doesn't exist")
> Exception Location: 	c:\Python344\lib\site-packages\MySQLdb\connections.py in query, line 280
> Python Executable: 	c:\Python344\python.exe
> Python Version: 	3.4.4
> Python Path: 	
> ['C:\\wamp\\www\\django\\usertest3',
>  'C:\\Windows\\system32\\python34.zip',
>  'c:\\Python344\\DLLs',
>  'c:\\Python344\\lib',
>  'c:\\Python344',
>  'c:\\Python344\\lib\\site-packages']
> Server time: 	Mon, 23 May 2016 02:57:54 +0430

why it selects/updates user from new table on login/repassword but only on register i get this error ? 
btw i can make superuser from command line ... that's how i tested login

**Comment by ubernostrum** [comment]
Have you read and followed [the instructions for using a custom user model with django-registration](https://django-registration.readthedocs.io/en/2.1.1/custom-user.html)?

**Comment by ubernostrum** [comment]
Closing for now; please reopen if you've got a test case which follows the above-linked instructions but still fails.
