### ISSUE TITLE
Can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by Kifsif** [ubernostrum/django-registration#43]
Hello, thanks for great app. The problem is below. 
Should you need to contact me: tmpgmv@mail.ru

Django==1.9.6
django-registration==2.0.4
Python 3.5.1

In settings: ACCOUNT_ACTIVATION_DAYS = 7

In other words I can doublecheck:

(photoarchive) michael@michael:~/workspace/photoarchive/photoarchive$ python manage.py shell
Python 3.5.1 (default, Dec 18 2015, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
|>>> import django
|>>> django.conf.settings.ACCOUNT_ACTIVATION_DAYS
7

Then I just run the tests. Everything is fine but one test:

(photoarchive) michael@michael:~/workspace/photoarchive/photoarchive$ python manage.py test registration
Creating test database for alias 'default'...
...........E................................/home/michael/workspace/venvs/photoarchive/lib/python3.5/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
  RemovedInDjango110Warning
# ..................
## ERROR: test_activation_expired (registration.tests.test_hmac_workflow.HMACViewTests)

Traceback (most recent call last):
  File "/home/michael/workspace/venvs/photoarchive/lib/python3.5/site-packages/registration/tests/test_hmac_workflow.py", line 110, in test_activation_expired
    user.date_joined - datetime.datetime.fromtimestamp(0)
TypeError: can't subtract offset-naive and offset-aware datetimes

**Comment by ubernostrum** [comment]
This was already fixed in `django-registration` 2.1. I may backport the fix and do a 2.0.5 release, but have't decided yet since it only affects the unit test and not the actual registration process.

**Comment by Kifsif** [comment]
Thank you very much.

**Comment by ubernostrum** [comment]
This is not going to be backported.
