### ISSUE TITLE
unique check on username is not executed

### ISSUE THREAD

**Issue by adsworth** [ubernostrum/django-registration#44]
With django-registration==2.1.0 and django==1.9.7 when trying to register a user that already exists in the database a "django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username" exception is raised and not handled. This seems to be because you override [clean](https://github.com/ubernostrum/django-registration/blob/master/registration/forms.py#L57) in forms.RegistrationForm and are not calling super().clean().

In  [\_\_init\_\_](https://github.com/django/django/blob/master/django/forms/models.py#L281) of Djangos forms.BaseModelForms the docs say "...self._validate_unique will be set to True by BaseModelForm.clean(). It is False by default so overriding self.clean() and failing to call super will stop validate_unique from being called ..."

**Comment by ubernostrum** [comment]
This looks like a bug due to oversight on my part for not calling `super()`. I'll get it fixed and push a release this weekend.

**Comment by ubernostrum** [comment]
This has been fixed, and `django-registration` 2.1.1 is on the Python Package Index now.
