### ISSUE TITLE
cleanupregistration now deletes all users

### ISSUE THREAD

**Issue by strindhaug** [ubernostrum/django-registration#46]
The changes in https://github.com/ubernostrum/django-registration/commit/626d8766a26a517b19f5399f132bc85a4f7ff274 does not check if the user `is_active` before deleting it.
Meaning the `cleanupregistration` management command now deletes every user ever registered before `ACCOUNT_ACTIVATION_DAYS` days ago.

We've had to restore the database on a customer server twice now because all the users disappeared, before we found this bug.

**Comment by strindhaug** [comment]
See https://github.com/ubernostrum/django-registration/pull/45/commits/8b6e5c35d2731fdb13ccb57b363ad2a7649ad41f for potential fix.

**Comment by ubernostrum** [comment]
I'm looking into this, but a bit confused because the behavior of `expired()` appears to be unit-tested. Going to fiddle with the test a bit to see if I can expose this.

**Comment by ubernostrum** [comment]
Fixed in e9c9e2c9d3bf6e0f02fe7e2b24b55360207be09f. Will roll a new release as soon as Travis passes it.

**Comment by ubernostrum** [comment]
2.1.2 is now live on PyPI and tagged on GitHub.
