### ISSUE TITLE
How to use tos

### ISSUE THREAD

**Issue by the-mace** [ubernostrum/django-registration#47]
Im using this for my URLs:
                  # Registration
                  url(r'^accounts/', include('registration.backends.hmac.urls')),

And a basic template for the registration form. All is working but i'd like to include the tos (terms of service) checkbox. 

I cant see how to do that easily. Any advice?

Thanks

**Comment by zuck** [comment]
```
from django.conf.urls import (include, url)
from registration.backends.hmac.views import RegistrationView

from .forms import CustomRegistrationWithTosForm


urlpatterns = [
    # ...
    url(r'^users/register/$', RegistrationView.as_view(form_class=CustomRegistrationWithTosForm), name='registration_register'),
]
```

**Comment by the-mace** [comment]
Thank you! Worked great.
