### ISSUE TITLE
The command cleanupregistration is potentially very destructive

### ISSUE THREAD

**Issue by strindhaug** [ubernostrum/django-registration#48]
The name "cleanupregistration" and the description "Delete expired user registrations from the database" implies that it deletes redundant junk left by the registration process.

But in reality this command deletes "junk" (users that registered and never logged in before it expired, which is helpful); but it also  it _deletes_ users that _have_ logged in (and thus have potentially have lots of associated data that could and worst case may actually be cascade deleted when the user is deleted), and then for some reason was explicitly deactivated by an admin rather than outright deleted.

This makes the difference between deactivating a user and deleting it pointless.  And it could unexpectedly delete lots of user generated content unless the admin has read the source code and realized that to ban a user but still keep their history and content; they must manually delete their registration profile first.

Unless you rename the management command to "deleteinactiveusers", I think the cleanup command should be changed to:
- Delete all RegistrationProfile that is ALREADY_ACTIVATED; but crucially _not_ it's associated user.
- Delete RegistrationProfile and the associated users when the activation_key is unused and the user is inactive. (Thus allowing them to try to registering again after the code expired, using the same email address, which is the main reason to run this command)

That would make this command fairly harmless, and do what it's supposed to.

(On a site where users are never explicitly deactivated by admins, the current behavior is harmless, but then [this part of the query](https://github.com/ubernostrum/django-registration/blob/e9c9e2c9d3bf6e0f02fe7e2b24b55360207be09f/registration/models.py#L77) is simply pointless, since the the all ALREADY_ACTIVATED profiles will be linked to an active user and thus excluded by the 'user__is_active=True' exclude filter. It's only when an admin explicitly chose to deactivate rather than delete a user this part of the filter will have any effect by deleting a user the admin not wanted deleted)

**Comment by ubernostrum** [comment]
The main use is that keeping the profile around lets you -- if you want to -- figure out who's inactive due to never having activated, and who's inactive because *you*, an admin of the site, deactivated their account for some reason. That has utility in some real-world user-banning schemes, which is why the data is kept around.

There's probably also auditing/history stuff that's relevant to some industries, but (even though I work in one of those industries) it's a less-relevant case most of the time.

**Comment by strindhaug** [comment]
@ubernostrum sure, but if you run the cleanupregistration regularly it will unexpectedly, just delete those you've deactivated manually.

In https://github.com/ubernostrum/django-registration/pull/49 i've changed the expired filter to exclude profiles where user is_active or activation_key is ACTIVATED so that it does not touch users that have actually logged in. (E.g. almost old behaviour but without potentially deleting users that are explicitly deactivated by admin)

I created a separate command to delete just the registration profile not the user for profiles that are ACTIVATED. So if you don't need to have them you can delete them automatically as well.

**Comment by ubernostrum** [comment]
I have a feeling the command's going to go away in a future release since it seems there's a major philosophical split of expected behavior. For now I'll leave it functioning as-is, but begin the deprecation process and document the use of `expired()` and how to build your own cleanup task from it.

**Comment by strindhaug** [comment]
If it should go away, then the other code must be changed somehow, so that when using email as username, you can re-register with the same email after the registration code has expired without the admin having to manually delete the user first. (Though I don't see how this can be achieved with the current model, without running something equivalent to the current or proposed cleanupregistration command either on schedule or automatically when the user attempts to re-register or use an expired code)

That's the main reason for running that command anyway, because otherwise users that let their code expire once may never register again without getting a new email address first...

**Comment by strindhaug** [comment]
Btw. I don't quite see how it's a matter of "philosophy" whether:
"Delete expired user registrations from the database"
should reasonably be expected to mean:
"Delete every inactive user in the system, except those registered within the last X days (or created manually)"

**Comment by ubernostrum** [comment]
I'm still unsure really what your complaint is here. The `expired()` query excludes any user with `is_active=True`, so there's no way it could delete an active user account. The documentation has always explained that there's a risk here when using the `is_active` field to also "ban" a user, and how to work around it. So I don't really understand what it is you want from the command.
