### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by Rulox** [ubernostrum/django-registration#5]
Hello!

In the django-registration Docs I read: "The 2.0 release of django-registration supports Django 1.7 and 1.8,"

I was wonder if the 2.0 release is out, because I would like to use the app with Django 1.8 but I can only install v1.0 using pip.

Thanks in advance.

**Comment by Rulox** [comment]
Btw, I could install manually from sources, but I think it would be nice to have v2.0 in PyPi if it is an stable version! ^^

Greetings

**Comment by ubernostrum** [comment]
2.0 has not been released yet, as you can verify from [the VERSION tuple](https://github.com/ubernostrum/django-registration/blob/master/registration/__init__.py). The documentation in the repository is being updated in anticipation of a release, and when the release happens it will be put on PyPI and tagged in this repository. Until that happens, there is no 2.0 release.
