### ISSUE TITLE
Impossible to catch activation errors

### ISSUE THREAD

**Issue by alorence** [ubernostrum/django-registration#50]
At the moment, on django-registration 2.1.2, there is no way to catch some common error case.

There is at least 2 common cases that could be helpful to catch:
1. The user copy /paste the right link, but after the allowed time window ended (link is outdated)
2. The user makes an error when copy / pasting the activation link. Or, since the activation email is sent as plain/text and some mail clients fail to automatically setup a link to the page, the user clicked on this kind of link:
   
   [http://server/accounts/activate/ImFudG9pbmVsb3JlbmNlIg](http://server/accounts/activate/ImFudG9pbmVsb3JlbmNlIg):1bGQdx:5ovhXqGm1JsYFVeCPYwDT8HmUx8/

In both case, the view simply loads the default template `registration/activate.html`. So there is no easy way to display a message to the user, to inform on what he can do now (depending on the error that happened). In addition, it could be useful for the administrator to also be notified in such cases. For example, a signal could be sent, or a callback function could be called.

Finally, when such an error happen, the user is not activated, and if the administrator doesn't do anything manually, the user will not have a chance to resolve his case. The only way out is to register again with another username (because it must be unique). This can lead to a many junk accounts created, if the user really want to create his account but don't understand why the activation link don't work for him.

**Comment by ubernostrum** [comment]
Need to think a bit about this one; it's a wart that's been in django-registration almost from the start, and I remember trying to solve it but don't remember why I didn't.

**Comment by tdruez** [comment]
@alorence you wrote:
>  Or, since the activation email is sent as plain/text and some mail clients fail to automatically setup a link to the page, the user clicked on this kind of link:
> http://server/accounts/activate/ImFudG9pbmVsb3JlbmNlIg:1bGQdx:5ovhXqGm1JsYFVeCPYwDT8HmUx8/

I think I am facing something similar. Do you know which email client would do such thing?

**Comment by ubernostrum** [comment]
This is being left open as a thing to do for django-registration 3.0, when that happens. It can't happen in the 2.x series because it's backwards-incompatible.

**Comment by ubernostrum** [comment]
Let me know what you think of c73a143bb42f886976a0aeb135bf6e675c291109 as a solutin.

**Comment by alorence** [comment]
Yeah, your changes seems to correctly address the original issue. I'm sorry I can't provide a stronger confirmation since I posted this issue 2 years ago, I found some workaround since, so I won't update the original project to try your fix.

**Comment by Mbiyu2017** [comment]
How do you make sure you have an activation link in the email sent to the user if you're email is in plaintext? I.e activation_email.txt ???
Is there a work around to make sure it works??
