### ISSUE TITLE
Impossible to send HTML emails on user registration

### ISSUE THREAD

**Issue by zuck** [ubernostrum/django-registration#52]
At the moment there's no way to send HTML-based emails on user registration on both **HMAC** and **model-based** backends, due to the way `User.user_email(...)` is used (without option to passing additional `**kwargs` or, at least, the `html_message`).

**Comment by ubernostrum** [comment]
I'm not sure what's missing from django-registration here; could you explain what's preventing you from subclassing the registration view and overriding the appropriate method to construct an HTML rather than a plain-text email?

**Comment by zuck** [comment]
Well, technically nothing, but I think HTML support should be a must-have feature for django-registration nowadays.

As explained in #50, as an example, to have plain-text activation emails without automatic link support could be a serious usability and logical issue!

At the same time, requiring the developer to override every time the `ActivationView` for such a common feature is very annoying and inefficient.

Finally, there is code redundancy among backends that could be removed as shown in #53.

**Comment by ubernostrum** [comment]
I'm not really a fan of adding more configuration for this (or, admittedly, of HTML email in general; it tends to be messy, impossible to get working cross-platform, and used for bad purposes). If there's a code-cleanup you think would be helpful, feel free to submit that separately, but for now django-registration will stick to plain-text mail. If you'd like to package up and distribute your own base classes which do HTML email, of course feel free to do so.

**Comment by phile314** [comment]
While I personally agree that HTML Emails are not the best idea, users actually do expect clickable links and not all email clients seem to insert them for plaintext emails. Having to subclass the registration view makes this use case much more difficult than it needs to be.

**Comment by zhuyuecai** [comment]
@ubernostrum just wandering is django-register supports html template for emails sending out now? 
From technical view point, this is tedious and not adding a lot value. 
But from business view point, this is a must. As a developer, we always get request to send out nice activation email, confirmation email etc to clients which is only available with html email template instead of txt. I think it is a must for this library.
