### ISSUE TITLE
Please update TEMPLATES test settings to django 1.8 (runtest broken with django >= 1.10)

### ISSUE THREAD

**Issue by absurd34** [ubernostrum/django-registration#55]
Hi James,

as documented here

https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/

django 1.8 added new style settings for 'TEMPLATES'. With upcoming django 1.10, the "old way" is no longer deprecated, but removed.

As registration does not officially support django < 1.8, that update can imho be done right away, w/o any compatibility considerations.

Fwiw, here is the patch I used with the Debian packaging:

https://anonscm.debian.org/cgit/python-modules/packages/python-django-registration.git/tree/debian/patches/update_django_runtest_settings_for_django110.patch

Thanks!

Stephan

**Comment by ubernostrum** [comment]
Leaving this open for now as a reminder to myself that this needs fixing when I do the run for 1.10 compat in the (near) future.

**Comment by ubernostrum** [comment]
This is fixed in master; tests are green on 1.8, 1.9 and 1.10.
