### ISSUE TITLE
How to enable custom admin action?

### ISSUE THREAD

**Issue by the-mace** [ubernostrum/django-registration#57]
Hi there, sorry for the basic question. I'd like to enable the custom admin-action to re-send the registration email but cant find out how to do that.

The only thing I found in the docs are this:
"Assuming you’re using the model-based workflow, a custom admin action is provided for this; in the admin for the RegistrationProfile model, simply click the checkbox for the user(s) you’d like to re-send the email for, then select the “Re-send activation emails” action."

But my Admin doesnt have that action. Other registration things are working fine.

Django 1.9.4, Python 2.7.10.

Thanks

**Comment by ubernostrum** [comment]
You'll need to manually enable it; check Django's admin documentation for how to add an admin action.
