### ISSUE TITLE
handle user form save failure

### ISSUE THREAD

**Issue by xrmx** [ubernostrum/django-registration#61]
We are getting IntegrityError in *create_inactive_user* in the model activation backend (but doesn't look backend specific) when the form is saved because of duplicated username.
We can catch IntegrityError in the backends and then pass the user as None to the callers or just catch it in *RegistrationView.form_valid*. We may add a *get_failure_url* in RegistrationView to redirect the user to somewhere else. What do you think?

**Comment by ubernostrum** [comment]
How are you getting duplicate username when the form checks for uniqueness? Do you often have many people trying to register the same username at the same time?

**Comment by xrmx** [comment]
I think it's the same user sending multiple requests at the same time each one running it its own transaction and the latest one committing failing.

**Comment by xrmx** [comment]
Silly me, that's 659f44d191ffac4d537dc54146b1a7a7e483c3da. Closing.
