### ISSUE TITLE
Usernick name check

### ISSUE THREAD

**Issue by cnc-club** [ubernostrum/django-registration#63]
Here's probably a bug:
https://github.com/incuna/django-registration/blob/master/registration/forms.py#L57

if there are already exist users having same nick names with different lettercase - .get will throw an error: 
MultipleObjectsReturned: get() returned more than one User -- it returned 3!

And so new user will be registered, probably filter with checking nuber of results will be more convinient.

**Comment by ubernostrum** [comment]
The code you've linked to is in a fork of django-registration. The code in the link does not exist in mainline django-registration, which subclasses Django's own `UserCreationForm` to inherit its base validation logic.
