### ISSUE TITLE
No reaction when callback for user_activated 

### ISSUE THREAD

**Issue by erikb85** [ubernostrum/django-registration#64]
Hi,

in the below code snippet you see two events being handled by sending an email. If I just add `user_registered` it works. But if I add the callback for `user_activated` nothing happens. Then even the `user_registered` event doesn't get handled. What can I do next? Do you see a mistake? if it's a bug can I trace it somehow? Events don't give much output.

```python
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.template import Context
from registration.signals import user_registered, user_activated

# the following function works if it is the only one
@receiver(user_registered)
def registered_callback(sender, **kwargs):
    EmailMessage(
        subject="activated",
        body=get_template("email_registered.txt").render(Context({
            'user' : 'FIXED',
        })),
        to=[
            "erik.bernoth@gmail.com",
        ],
    ).send()

#if this one is added or the only function nothing happens
@receiver(user_activated)
def registered_callback(sender, **kwargs):
    EmailMessage(
        subject="activated",
        body=get_template("email_registered.txt").render(Context({
            'user' : 'FIXED',
        })),
        to=[
            "erik.bernoth@gmail.com",
        ],
    ).send()
```

Pip freeze on the Ubuntu 14.04 dev system with Python 3.4.3:
```
Django==1.10.3
django-bootstrap3==7.1.0
django-registration==2.1.2
mysqlclient==1.3.9
```

(System Update is no option because customer doesn't want that to happen)

**Comment by ubernostrum** [comment]
I'm unsure what the issue is, but the django-users mailing list is likely a better place to take the question.

**Comment by erikb85** [comment]
What should they know about django-registration? Usually adding a callback to django signals works. It's just when you add a callback to `registration.signals.user_activated`, suddenly ALL callbacks don't work anymore.

**Comment by ubernostrum** [comment]
It's unlikely that anything specific to django-registration is involved here. The test suite of django-registration verifies that signals are sent correctly.

So the most likely explanation is something else is going on that you haven't figured out (probably an exception being raised in one of your signal handlers), and the place to ask about that is the django-users mailing list, or the #django IRC channel on freenode.

**Comment by ubernostrum** [comment]
Actually no, the most likely explanation is you gave the same name to both of your receiver functions. That's a step further back, in Python: naming two things the same name will cause you problems.
