### ISSUE TITLE
Actiovation code - BadSignature after change form class in registration

### ISSUE THREAD

**Issue by jorej** [ubernostrum/django-registration#67]
I've noticed strange situation. When I have url:

`
auth_patterns = [
    url(r'^', include('registration.backends.hmac.urls')),
]

urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(HomeView.as_view()), name='index'),
    url(r'^accounts/', include(auth_patterns)),
)
`

everything works fine, but when I force unique email adress

`
url(r'^register/$',
        RegistrationView.as_view(form_class=RegistrationFormUniqueEmail),
        name='registration_register'
    ),
`
Email is sending, but when I click on activation link i get activate.html (which is rendered when activation fails). I tried to debug registration app and I've noticed that this issue is propably in this fragment of code. (registration.backends.hmac.views.ActivationView)

`
def validate_key(self, activation_key):
    """
    Verify that the activation key is valid and within the
    permitted activation time window, returning the username if
    valid or ``None`` if not.

    """
    try:
        username = signing.loads(
            activation_key,
            salt=REGISTRATION_SALT,
            max_age=settings.ACCOUNT_ACTIVATION_DAYS * 86400
        )
        return username
    # SignatureExpired is a subclass of BadSignature, so this will
    # catch either one.
    except signing.BadSignature:
        return None
`

It returns None so try-code throwing BadSignature, but why?

**Comment by ubernostrum** [comment]
Much like the last reported issue, it is highly unlikely a bug in django-registration is causing this. Please consider using a general Django-help forum such as the django-users mailing list, the #django IRC channel on Freenode, or the /r/django subreddit.
