### ISSUE TITLE
activation_key must be unique

### ISSUE THREAD

**Issue by LennyLip** [ubernostrum/django-registration#70]
RegistrationProfile.activation_key must be uniqie=True, because we use "get" by 
https://github.com/ubernostrum/django-registration/blob/master/registration/models.py#L52

also ALREADY_ACTIVATED , i think, better change to activation datetime field.

**Comment by ubernostrum** [comment]
You seem to have closed this yourself, but: the model-based backend is only in django-registration now for backwards-compatibility purposes, and will likely be removed in 3.0. Since it exists only to provide backwards compatibility, it will never have backwards-incompatible changes made to it.
