### ISSUE TITLE
Custom user model urls

### ISSUE THREAD

**Issue by dmwyatt** [ubernostrum/django-registration#71]
If I configure my urls.py as mentioned in the [documentation](https://django-registration.readthedocs.io/en/2.2/custom-user.html#overview) for custom user models, I wasn't getting the registration complete view/template when redirected to `/register/complete/`.  It was just rendering the registration view and form again.  I also had to include the following:

```
url(r'^accounts/register/complete/$',
	    TemplateView.as_view(
		    template_name='registration/registration_complete.html'
	    ),
	    name='registration_complete')
```

**Comment by ubernostrum** [comment]
Did you also `include` the remaining URLs as mentioned in the documentation?
