### ISSUE TITLE
Activation key: stop reinventing the wheel

### ISSUE THREAD

**Issue by breard-r** [ubernostrum/django-registration#8]
For no obvious reasons, [the activation key is generated](https://github.com/ubernostrum/django-registration/blob/master/registration/models.py#L99-L103) with a custom process involving a SHA-1. There is absolutely no reason to reinvent such a key generation function because [django already provides a much better one](https://github.com/django/django/blob/master/django/utils/crypto.py#L54-L56).

**Comment by ubernostrum** [comment]
The obvious reason is that django-registration dates back to 2007, when Django didn't provide such a thing. It's on my list to look at, but there are some backwards-compatibility concerns to think about.

**Comment by ubernostrum** [comment]
Fixed in 88212178df7138a21620bd73280f1d49eba6d7d0.

**Comment by breard-r** [comment]
Thank you for your explanations and using my suggestion. However, I have to say you didn't used it as expected and therefore I have a question: why keeping the sha1? And why using the username in the sha1? Both are completely useless here.
