### ISSUE TITLE
Template names

### ISSUE THREAD

**Issue by Thyrst** [ubernostrum/django-registration#80]
For what reason are template names hard coded in view functions!? It would be very nice if someone could use custom templates...

**Comment by AlleoNET** [comment]
You can use cusotm templates. Create folder "templates" and in settings set:
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,  'templates'),
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

**Comment by ubernostrum** [comment]
You can override the templates the same way you can for any other class-based view in Django. Please have a look at the Django documentation for details.
