### ISSUE TITLE
'RegistrationView' object has no attribute 'request' w/ registration.backends.hmac.views.py

### ISSUE THREAD

**Issue by billbunkum** [ubernostrum/django-registration#83]
The error occurs on **line 77** of registration.backends.hmac.views.py when the `get_current_site(self.request)` method is called. It is called within another method `get_email_context(self, activation_key)`

**Comment by ubernostrum** [comment]
That line is exercised by the test suite on all combinations of supported Python and Django versions, and does not raise an error. And all class-based views have a `request` attribute associated with them, which would mean if you're seeing that error something is very broken in your copy of Django.

**Comment by billbunkum** [comment]
Thanks for your time and the reply, James! That'll give me a starting point
for further debugging.

-Will Hurst
https://billbunkum.github.io/
+1 (859)312 1325

"The good traveler has no fixed plans and is not intent on arriving." – Lao
Zi
