### ISSUE TITLE
Handle SMTP error 550

### ISSUE THREAD

**Issue by oxivanisher** [ubernostrum/django-registration#90]
Hi There

It seems, that django-registration does not handle the SMTP error 550. This error is probably not seen widely, since it is often disabled for anti spam measures. I only got it when I tried to register a user in the same email domain as the used SMTP transfer address. Never the less, the error should be handled correctly and not break the application.

I added a renamed HTML django stack-trace: 
[SMTPRecipientsRefused+at+_accounts_register_.html.txt](https://github.com/ubernostrum/django-registration/files/1038595/SMTPRecipientsRefused.at._accounts_register_.html.txt)

BR,
oXiVanisher

**Comment by ubernostrum** [comment]
This isn't really something django-registration can help with; allowing the exception to propagate is the only way to let you know something has gone wrong.

**Comment by sebhaase** [comment]
Is there a good way to respond to failure while sending the registration email?  In other words,  when the exception SMTPRecipientsRefused  occurs inside
```
File ".../django_registration/backends/activation/views.py" in register
  40.         new_user = self.create_inactive_user(form)

File "...views.py" in create_inactive_user
           self.send_activation_email(new_user)
```
Is the user already created or could this be unrolled so that there would not be a left over user which can never get activated?
Thanks.
