### ISSUE TITLE
Leaking of password reset token through the reset url 

### ISSUE THREAD

**Issue by joshblum** [ubernostrum/django-registration#94]
I think it is possible to leak the password reset token since it is left in the url. 

In Django 1.11 the token is stripped during a redirect ([docs](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-contrib-auth), [code](https://github.com/django/django/blob/1.11.2/django/contrib/auth/views.py#L461)) to prevent the token from being taken in the referrer header from 3rd party apps on the page. I haven't dug too deeply into the source for this project but at a first glance it seems that the vulnerability exists since the older auth view functions are used and not the class based views.

If this is the case would be happy to help fix similar to [django-registration-redux](https://github.com/macropin/django-registration/pull/268), or at the very least alert you to the issue. Let me know if you guys need any help!

**Comment by ubernostrum** [comment]
The workaround you've provided won't work in django-registration, because django-registration has a hard policy of never shipping templates, which means that adding workaround code to default templates is not an option here.

Best that can be done is to document the need to be careful, and encourage people to upgrade to a more modern version of Django.

**Comment by joshblum** [comment]
Since django-registration supports django 1.11 it should at least use the newer class based views if available instead of the current deprecrated function based views: https://github.com/ubernostrum/django-registration/blob/master/registration/auth_urls.py#L50

Even if a user is on a newer version of django they won't benefit from the new functions unless a change is made here: https://github.com/macropin/django-registration/pull/268/files#diff-c74bf13c33882d3a4d3aaf1ffc1738d7R31
