### ISSUE TITLE
Password reset for missing email fails

### ISSUE THREAD

**Issue by LiamK** [ubernostrum/django-registration#96]
Hi,
Maybe I have missed something here but I think this is a bug.  I'm using v. 2.1.2.  With HMAC activation.
Using the password reset functionality, if the user enters an email address which is not in the system,
registration responds with 

> Password reset successful
> We've e-mailed instructions for setting your password to the e-mail address you provided. You should be receiving it shortly.

However, no email is sent (of course).  This is confusing.

The desired behavior is to notify the user immediately that no account matching that email address was found.
(Also, should handle multiple accounts with the same email address by sending multiple emails?)

Any help very much appreciated.
Thanks,
Liam

**Comment by ubernostrum** [comment]
I'm unsure how this could happen since django-registration provides no templates and thus could not display that message.
