### ISSUE TITLE
Use another HTTP code for the invalid activation link response?

### ISSUE THREAD

**Issue by schtibe** [ubernostrum/django-registration#97]
Let me shortly explain why this could be of use:
I just had the situation where customer reported that they can't use the activation link that was sent by email to them. By checking the logs I am pretty sure that the problem must be because some 3rd party software is pre-fetching the links from the email, thus activating the user and rendering the link invalid. Of course, the user was still activated, but was prompted with an error message which confused most of them.
Anway, what I noticed is that when looking at the logs, a HTTP response code different than 200 would be nice for debugging purposes. Maybe 400 Bad Request or 409 Conflict or even 410 Gone?

**Comment by ubernostrum** [comment]
This is a variant of #50 and unfortunately any fix will be backwards-incompatible, which means it can't happen until 3.0. Going to close this and leave #50 open as the reminder to overhaul how activation is handled.
