### ISSUE TITLE
scheme definition for email links

### ISSUE THREAD

**Issue by sybix** [ubernostrum/django-registration#98]
I'm trying to get http or https link in the activation link when sending email, without hardcoding the scheme

as we don't have access to request in the email templating, i have done a patch to access scheme in mail.

Maybe i'm doing the wrong way, but for now it's work as a workaround. Is a recommended way for doing this ? 

If not i think this is a usefull feature for django-registration user.

I doubt i have done thing the right way but the patch : 

[add_scheme_activation_mail.txt](https://github.com/ubernostrum/django-registration/files/1121183/add_scheme_activation_mail.txt)

**Comment by ubernostrum** [comment]
Could you please file a pull request if you're trying to submit a patch?
